[opener]
pdf = [
    { run = 'zen-browser "%s"', orphan = true, desc = "Zen Browser" },
    { run = 'onlyoffice-desktopeditors "%s"', orphan = true, desc = "OnlyOffice" }
]

[open]
rules = [
    { mime = "application/pdf", use = "pdf" },
]
