[opener]

pdf = [
  { run = 'zen-browser "%s"', orphan = true, desc = "Zen Browser" },
  { run = 'onlyoffice-desktopeditors "%s"', orphan = true, desc = "OnlyOffice" }
]

micro = [
  { run = 'micro "%s"', block = true, desc = "Micro Editor" }
]

[open]

prepend_rules = [
  { mime = "application/pdf", use = ["pdf", "reveal"] },
  { mime = "application/{json,ndjson}", use = ["micro"] },
  { url = "*.json", use = ["micro"] },

  { mime = "text/*", use = ["micro"] }
]
